CREATE TABLE Comment (
	Id INT PRIMARY KEY AUTO_INCREMENT,
	Descr VARCHAR(1000) NOT NULL,
	IsSolution TINYINT NOT NULL,
	AuthorId INT,
	ErrorId INT NOT NULL,
	FOREIGN KEY (AuthorId) references User(Id) ON DELETE SET NULL,
	FOREIGN KEY (ErrorId) REFERENCES Error(Id) ON DELETE CASCADE
);